version: "3.8"

services:
  app:
    build: .
    container_name: laravel83-app
    volumes:
      - .:/var/www
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    container_name: laravel83-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
